### ISSUE TITLE
Deprecated elements & attributes

### ISSUE THREAD

**Issue by artyuum** [jozo/all-html-elements-and-attributes#2]
It would be a nice addition to distinguish deprecated elements & deprecated attributes. If you're okay I can try to update your script to include that.

**Comment by jozo** [comment]
Sure, go ahead. PRs are welcome. :slightly_smiling_face:

**Comment by artyuum** [comment]
Would you like to keep both json files separate or is it fine if I re-structure them into a single json with the following structure?
Or maybe create a third json file with this structure?

```json
{
    "*": {
        "deprecated": false,
        "attributes": [
            { "name": "accesskey", "deprecated": false },
            { "name": "class", "deprecated": false },
            ...
        ]
    },
    "a": {
        "deprecated": false,
        "attributes": [
            { "name": "download", "deprecated": false },
            { "name": "href", "deprecated": false },
            ...
        ]
    },
    "abbr": {
        "deprecated": false,
        "attributes": []
    },
    ...
}

```

**Comment by jozo** [comment]
Single file with this structure sounds good 👍️
